language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"  # PyPy2 2.5.0
  - "pypy3"
  - "pypy-5.3.1"

install:
    python setup.py install && pip install -U pip zope.interface

script: python -m unittest plumber.tests
